// <auto-generated />
namespace HarfArdehAssociation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addGroupTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addGroupTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201411261021106_addGroupTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
